# Generated by Django 2.2.7 on 2019-12-05 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjetas', '0004_auto_20191205_1434'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.Tarjeta')),
            ],
        ),
    ]
