# Generated by Django 2.2.7 on 2019-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField()),
                ('visibilidad', models.CharField(max_length=200)),
            ],
        ),
    ]
