# Generated by Django 2.2.7 on 2019-12-06 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableros', '0002_tablero_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablero',
            name='miembros',
            field=models.ManyToManyField(related_name='miembros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='visibilidad',
            field=models.CharField(choices=[('V', 'Visible'), ('N', 'No Visible')], max_length=1),
        ),
    ]
