# Generated by Django 2.2.7 on 2019-12-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='tablero',
            new_name='favoritos',
        ),
    ]
