# Generated by Django 2.2.7 on 2019-12-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        ('tarjetas', '0002_remove_tarjeta_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='miembros',
            field=models.ManyToManyField(to='miembros.Miembro'),
        ),
    ]
