# Generated by Django 2.2.7 on 2019-12-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_tarjeta_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='miembros',
            field=models.ManyToManyField(to='tableros.Tablero'),
        ),
    ]
