# Generated by Django 2.2.7 on 2019-12-06 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0004_auto_20191205_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='miembros',
            field=models.ManyToManyField(related_name='suscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
