# Generated by Django 2.2.7 on 2019-12-06 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjetas', '0005_auto_20191206_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='dueño',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='miembros',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='Dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dueño', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='Miembros',
            field=models.ManyToManyField(related_name='Miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
